# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1154480f701ae32ee1de7ebebea7bc79c5677f5cd349529c61203e064966c2aefbd1502bbc92a314202cab1c92a92368729ec63982029a38aee5905e7b30c4e

test:
  secret_key_base: dd82f20bda7bd54e93e877dbfac0fe94dc9f34f15eb5d1582e13ea4c1dc78285be5e4eb69ae357641631b0b66cccea9fc100dce4ad19dd3269a48bf012740333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
